### ISSUE TITLE
SBDFileMessage crashing on access to url parameter

### ISSUE THREAD

**Issue by diegocichello** [smilefam/sendbird-ios-framework#41]
Hello, my company are using SendBird for a while now, and we found a specific case that the app is crashing when trying to access the .url parameter from a SBDFileMessage.

The crash is this one:

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSFrozenDictionaryM _fastCStringContents:]: unrecognized selector sent to instance 0x6000004c1c60'

When I try to po the fileMessage that's crashing this is what it returns:

<SBDFileMessage, 0x600000981b80, super class: <SBDFileMessage, 0x600000981b80, super class: <SBDFileMessage: 0x600000981b80>, message id: 2112538573, channel url: sendbird_group_channel_42253_554b47be3e2ba10260eb2f1ffa6092707cb4b36c, channel type: group, data: , custom type: , created at: 1548933930263, request id: >, file url: {
}, file name: MAO  ESPECIALIZADA  CLIENTE VICTOR CUNHA.pdf>

It looks like it's treating the url as a dictionary and not as a String. Dunno what is really happening. But this started ocurring on the latest builds.

**Comment by famous90** [comment]
Hey @diegocichello could you let me know more information about SDK you use. I can solve easily if you give me follow information.
The previous version and current version of SDK, Which method do you use to send message, What parameters did you pass to the method, Did you get the message from event or api?

**Comment by sf-jed-kyung** [comment]
We are investigating this issue on the server-side. Would you open a support ticket with your SendBird App ID at our [Technical Support](https://help.sendbird.com/hc/en-us/requests/new)?

Don't post your App ID here.

**Comment by sf-jed-kyung** [comment]
You don't have to open a support ticket. We found the server logs of your issue.

**Comment by diegocichello** [comment]
Okay! No problem than, you guys still need the information requested?

**Comment by sf-jed-kyung** [comment]
It's ok. We figured out that JavaScript SDK sends a file message with a dictionary type as a file URL when the file uploading is failed. We're going to release the new version this week, but the old messages that have a dictionary in the file URL will keep causing the same issue. To prevent it, we have to update our server and it could take some time. Probably, the server would return an empty string instead of a dictionary after updating. I think this is the best solution that we have.

In the meantime, please check the type of the file URL property. We are really sorry for causing you any trouble.

**Comment by diegocichello** [comment]
Okay let me know when u guys release the fixed version pls!

**Comment by sf-jed-kyung** [comment]
JavaScript SDK was fixed in v3.0.94. I'll notify you again when the server is updated.

**Comment by sf-jed-kyung** [comment]
@diegocichello The server was updated a few days ago. If you see the same issue, let me know. Thanks.
